// packages/web/src/uikit/components/stack.vue
<template>
  <div class="ui-stack" :style="style"><slot /></div>
</template>

<script setup lang="ts">
import { StyleValue } from "vue";

const props = defineProps<{
  column?: boolean;
  columnRev?: boolean;
  row?: boolean;
  rowRef?: boolean;
  alignItems?: "flex-start" | "flex-end" | "center";
  justifyContent?: "flex-start" | "flex-end" | "center" | "space-between";
  wrap?: boolean;
  gap?: number;
  fullWidth?: boolean;
}>();

const style: StyleValue = {
  flexDirection: props.row
    ? "row"
    : props.rowRef
    ? "row-reverse"
    : props.column
    ? "column"
    : props.columnRev
    ? "column-reverse"
    : "row",
  alignItems: props.alignItems ?? "flex-start",
  justifyContent: props.justifyContent ?? "flex-start",
  flexWrap: props.wrap ? "wrap" : undefined,
  gap: `${(props.gap ?? 0) * 8}px`,
  width: props.fullWidth ? "100%" : undefined,
};
</script>

<style lang="scss">
.ui-stack {
  display: flex;
}
</style>

// packages/mobile/src/components/Stack/Stack.tsx
import React from "react";
import { StyleSheet, View } from "react-native";

export interface StackProps {
  children: any;
  row?: boolean;
  rowRef?: boolean;
  column?: boolean;
  columnRef?: boolean;
  alignItems?: "flex-start" | "flex-end" | "center" | "stretch" | "baseline";
  justifyContent?:
    | "flex-start"
    | "flex-end"
    | "center"
    | "space-between"
    | "space-around"
    | "space-evenly";
  wrap?: boolean;
  fullWidth?: boolean;
}

export const Stack: React.FC<StackProps> = (props: StackProps) => {
  const {
    children,
    row,
    rowRef,
    column,
    columnRef,
    alignItems,
    justifyContent,
    wrap,
    fullWidth,
  } = props;

  const styles = React.useMemo(
    () =>
      StyleSheet.create({
        root: {
          display: "flex",
          flexDirection: row
            ? "row"
            : rowRef
            ? "row-reverse"
            : column
            ? "column"
            : columnRef
            ? "column-reverse"
            : "row",
          alignItems,
          justifyContent,
          wrap,
          width: fullWidth ? "100%" : undefined,
        },
      }),
    [
      alignItems,
      column,
      columnRef,
      fullWidth,
      justifyContent,
      row,
      rowRef,
      wrap,
    ]
  );

  return <View style={styles.root}>{children}</View>;
};
